import requests
from bs4 import BeautifulSoup
from datetime import datetime
from urllib.parse import urljoin
import pyodbc
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import logging
import os

BASE_URL = "https://www.justice.gov"
PARDONS_URL = f"{BASE_URL}/pardon/clemency-grants-president-donald-j-trump-2025-present"

# Email config
FROM_EMAIL = "it@tmz.com"
SMTP_SERVER = "mx0a-00195501.pphosted.com"
SMTP_PORT = 25
TO_EMAILS = [
    "Jennifer.Delgado@tmz.com",
    "Kevin.King@tmz.com",
    "marlee.chartash@tmz.com",
    "Priscilla.Hwang@tmz.com",
    "Shirley.Troche@tmz.com"
]

# Logging setup
LOG_DIR = 'u:/docketwatch/python/logs'
os.makedirs(LOG_DIR, exist_ok=True)
SCRIPT_NAME = os.path.splitext(os.path.basename(__file__))[0]
LOG_FILE = f"{LOG_DIR}/{SCRIPT_NAME}.log"
try:
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(LOG_FILE, encoding='utf-8'),
            logging.StreamHandler()
        ]
    )
    logging.info(f"Logging initialized: {LOG_FILE}")
except Exception as e:
    print(f"Failed to initialize logging: {e}")

def send_pardon_email(name, district, sentenced, offense, pardon_date, link):
    subject = f"DocketWatch Alert: New Presidential Pardon – {name}"
    # Build a simple, clean HTML body with key details
    safe_link = link or f"{PARDONS_URL}"
    date_str = pardon_date.strftime('%B %d, %Y') if hasattr(pardon_date, 'strftime') else str(pardon_date)
    body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #222; line-height: 1.45;">
        <h2 style="margin: 0 0 10px;">New Presidential Pardon</h2>
        <p style="margin: 0 0 14px;">
            <strong>Name:</strong> {name}<br/>
            <strong>District:</strong> {district}<br/>
            <strong>Sentenced:</strong> {sentenced}<br/>
            <strong>Offense:</strong> {offense}<br/>
            <strong>Pardon Date:</strong> {date_str}
        </p>
        <p style="margin: 0 0 14px;">
            <a href="{safe_link}" style="color:#0b63ce;">View details on justice.gov</a>
        </p>
        <hr style="border:none;border-top:1px solid #eee;margin:16px 0;"/>
        <p style="font-size:12px;color:#666;margin:0;">
            This alert was generated by DocketWatch. Source: <a href="{PARDONS_URL}">{PARDONS_URL}</a>
        </p>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["From"] = FROM_EMAIL
    msg["To"] = ", ".join(TO_EMAILS)  # Header shows all recipients
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            # The third argument must be a LIST of emails, not a string
            server.sendmail(FROM_EMAIL, TO_EMAILS, msg.as_string())
        logging.info(f"Email sent for new pardon {name} (body_len={len(body)})")
        print(f"ALERT: Email sent for new pardon {name}")
    except Exception as e:
        logging.error(f"Failed to send email for {name}: {e}")
        print(f"ERROR: Failed to send email for {name}: {e}")


def main():
    try:
        conn = pyodbc.connect("DSN=Docketwatch;TrustServerCertificate=yes;")
        cursor = conn.cursor()
        logging.info("DB connection established")
    except Exception as e:
        logging.critical(f"Could not connect to DB: {e}")
        print(f"ERROR: Could not connect to DB: {e}")
        return

    try:
        resp = requests.get(PARDONS_URL, timeout=30)
        resp.raise_for_status()
        logging.info(f"Fetched pardons page OK: {PARDONS_URL}")
    except Exception as e:
        logging.error(f"Failed to fetch pardons page: {e}")
        print(f"ERROR: Failed to fetch pardons page: {e}")
        return

    soup = BeautifulSoup(resp.content, "html.parser")
    h3_list = soup.find_all("h3")

    inserted = 0
    skipped = 0
    total_rows = 0

    for h3 in h3_list:
        h3_text = h3.get_text(strip=True)
        if " - " in h3_text:
            date_str = h3_text.split(" - ")[0].strip()
        else:
            date_str = h3_text.strip()
        try:
            pardon_date = datetime.strptime(date_str, "%B %d, %Y").date()
        except Exception as ex:
            logging.warning(f"Skipping h3 with bad date format: {h3_text}")
            print(f"WARNING: Skipping h3 with bad date format: {h3_text}")
            continue

        table = h3.find_next_sibling("table")
        if not table:
            logging.warning(f"No table found after header: {h3_text}")
            print(f"WARNING: No table found after header: {h3_text}")
            continue

        rows = table.find_all("tr")
        for i, row in enumerate(rows, 1):
            cells = row.find_all("td")
            if len(cells) < 4:
                continue

            name = cells[0].get_text(strip=True)
            district = cells[1].get_text(strip=True)
            sentenced = cells[2].get_text(strip=True)
            offense = cells[3].get_text(strip=True)
            link_tag = cells[0].find("a")
            link = urljoin(BASE_URL, link_tag["href"]) if link_tag else None

            # Deduplication check: by BOTH name and pardon_date
            cursor.execute(
                "SELECT COUNT(*) FROM docketwatch.dbo.pardons WHERE name = ? AND pardon_date = ?",
                (name, pardon_date)
            )
            already_exists = cursor.fetchone()[0] > 0
            if already_exists:
                skipped += 1
                continue

            # Insert
            try:
                cursor.execute(
                    """
                    INSERT INTO docketwatch.dbo.pardons
                        ([name],[district],[sentenced],[offense],[pardon_date],[link],[timestamp])
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (name, district, sentenced, offense, pardon_date, link, datetime.now())
                )
                inserted += 1
                logging.info(f"Inserted pardon row: {name} / {pardon_date}")
                print(f"Inserted: {name} / {pardon_date}")

                # Send email alert
                send_pardon_email(name, district, sentenced, offense, pardon_date, link)

            except Exception as ex:
                logging.error(f"DB insert failed for {name} ({pardon_date}): {ex}")
                print(f"ERROR: DB insert failed for {name} ({pardon_date}): {ex}")

            total_rows += 1

    try:
        conn.commit()
        cursor.close()
        conn.close()
        logging.info(f"Done! Inserted: {inserted}, Skipped: {skipped}")
    except Exception as e:
        logging.error(f"Final DB commit/close error: {e}")
        print(f"ERROR: Final DB commit/close error: {e}")

    print(f"\nDone! Inserted: {inserted}, Skipped (already in DB): {skipped}")

if __name__ == "__main__":
    main()
